// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TelemetryApi.Data;

#nullable disable

namespace TelemetryApi.Migrations
{
    [DbContext(typeof(VendingDbContext))]
    [Migration("20260308045302_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TelemetryApi.Models.MachineState", b =>
                {
                    b.Property<string>("MachineId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<DateTime?>("TsUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MachineId");

                    b.ToTable("MachineState");
                });

            modelBuilder.Entity("TelemetryApi.Models.Telemetry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TemperatureC")
                        .HasColumnType("float");

                    b.Property<DateTime?>("TsUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Telemetry");
                });
#pragma warning restore 612, 618
        }
    }
}
